name: Deploy on PR

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes in infrastructure
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            infrastructure/**
            terraform/**

      - name: Set up AWS credentials
        if: steps.changes.outputs.any_changed == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Terraform
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve